---
aro_creds_file_path: "{{ playbook_dir }}/../aro.creds"
aro_creds_user_file_path: "{{ playbook_dir }}/../user.creds"

# likely expose via navigator volume mount
aro_creds_ansible_ssh_private_key_file: "/root/keys/my_priv_key"
aro_creds_ansible_ssh_pub_key_file: "/root/keys/my_pub_key.pub"
aro_creds_aap_manifest_pah: "/root/manifests/manifest.zip"

aro_creds_openshift_admin_password: "{{ lookup('env', 'K8S_AUTH_PASSWORD') }}"
aro_creds_aap_machine_cred_password: "{{ lookup('env', 'AAP_MACHINE_CRED_PASSWORD') }}"
aro_creds_aap_admin_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
aro_creds_aap_machine_cred_priv_key: "{{ lookup('file', aro_creds_ansible_ssh_private_key_file) }}"
aro_creds_aap_machine_cred_pub_key: "{{ lookup('file', aro_creds_ansible_ssh_pub_key_file) }}"
aro_creds_aap_operator_chatbot_token: "{{ lookup('env', 'K8S_AUTH_PASSWORD') }}"
