---
user_creds_file_path: "{{ playbook_dir }}/../user.creds"

# likely expose via navigator volume mount
user_creds_ansible_ssh_private_key_file: "/root/keys/my_priv_key"
user_creds_ansible_ssh_pub_key_file: "/root/keys/my_pub_key.pub"
user_creds_aap_manifest_pah: "/root/manifests/manifest.zip"

user_creds_openshift_admin_password: "{{ lookup('env', 'K8S_AUTH_PASSWORD') }}"
user_creds_aap_machine_cred_password: "{{ lookup('env', 'AAP_MACHINE_CRED_PASSWORD') }}"

user_creds_aap_admin_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
user_creds_aap_machine_cred_priv_key: "{{ lookup('file', user_creds_ansible_ssh_private_key_file) }}"
user_creds_aap_machine_cred_pub_key: "{{ lookup('file', user_creds_ansible_ssh_pub_key_file) }}"
user_creds_aap_operator_chatbot_token: "{{ lookup('env', 'K8S_AUTH_PASSWORD') }}"
